version: '3.8'

services:
  app:
    build: ./app
    container_name: jira_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      # Дополнительные переменные, если нужны
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/jira
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      MAIL_LOGIN: ${MAIL_LOGIN}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      OAUTH_GITHUB_ID: ${OAUTH_GITHUB_ID}
      OAUTH_GITHUB_SECRET: ${OAUTH_GITHUB_SECRET}
      OAUTH_GOOGLE_ID: ${OAUTH_GOOGLE_ID}
      OAUTH_GOOGLE_SECRET: ${OAUTH_GOOGLE_SECRET}
      OAUTH_GITLAB_ID: ${OAUTH_GITLAB_ID}
      OAUTH_GITLAB_SECRET: ${OAUTH_GITLAB_SECRET}
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: jira_db
    restart: always
    environment:
      POSTGRES_DB: jira
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: jira_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app/resources:/opt/jirarush/resources:ro
    depends_on:
      - app

volumes:
  pgdata: