app:
  host-url: http://localhost:8080
  test-mail: ${MAIL_LOGIN}
  templates-update-cache: 5s
  mail-sending-props:
    core-pool-size: 8
    max-pool-size: 100

spring:
  config:
    import: "optional:classpath:application-secrets.properties"
  init:
    mode: never
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20
  messages:
    basename: messages
    encoding: UTF-8

  datasource:
    url: jdbc:postgresql://localhost:5432/jira
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  liquibase:
    changeLog: "classpath:db/changelog.sql"

  jackson:
    visibility:
      field: any
      getter: none
      setter: none
      is-getter: none

  cache:
    cache-names: users
    caffeine.spec: maximumSize=10000,expireAfterAccess=5m

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${OAUTH_GITHUB_ID}
            client-secret: ${OAUTH_GITHUB_SECRET}
            scope: [ email ]
          google:
            client-id: ${OAUTH_GOOGLE_ID}
            client-secret: ${OAUTH_GOOGLE_SECRET}
            scope: [ email, profile ]
          gitlab:
            client-id: ${OAUTH_GITLAB_ID}
            client-secret: ${OAUTH_GITLAB_SECRET}
            client-name: GitLab
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: read_user
        provider:
          gitlab:
            authorization-uri: https://gitlab.com/oauth/authorize
            token-uri: https://gitlab.com/oauth/token
            user-info-uri: https://gitlab.com/api/v4/user
            user-name-attribute: email

  sql:
    init:
      mode: always

  mail:
    properties:
      mail:
        smtp:
          starttls.enable: true
          auth: true
    host: smtp.gmail.com
    username: ${MAIL_LOGIN}
    password: ${MAIL_PASSWORD}
    port: 587

  thymeleaf.check-template-location: false
  mvc.throw-exception-if-no-handler-found: true
  web.resources.add-mappings: false

logging:
  level:
    root: INFO
    com.javarush.jira: DEBUG
    com.javarush.jira.common.config.MvcConfig: WARN
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG
    org.springframework.web: DEBUG
    org.springframework.http: DEBUG

server:
  forward-headers-strategy: framework
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

springdoc.swagger-ui.path: /doc
